<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>.spl</string>
   </array>
  <key>name</key>
  <string>ExStream</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.ExStream</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>( \- )</string>
          <key>name</key>
          <string>constant.other.symbol.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+)</string>
          <key>name</key>
          <string>constant.other.symbol.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*)</string>
          <key>name</key>
          <string>constant.other.symbol.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$.*)</string>
          <key>name</key>
          <string>comment.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(set)</string>
          <key>name</key>
          <string>entity.name.class.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(inStreamCount|pastCount|past)</string>
          <key>name</key>
          <string>string.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(s([0-9]*)*)</string>
          <key>name</key>
          <string>keyword.ExStream</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\.(in|out))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.ExStream</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(([0-9]*)*)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.ExStream</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <dict>
      <key>include</key>
      <string>#numeric</string>
    </dict>

    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\(?:\\|&quot;))</string>
          <key>name</key>
          <string>text.ExStream</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.ExStream</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\-)?\d+)</string>
          <key>name</key>
          <string>constant.numeric.ExStream</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
